# Generated by Django 4.0.4 on 2022-05-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('phone_number', models.CharField(default='+996', max_length=50, verbose_name='Номер Телефона')),
                ('porter', models.BooleanField(verbose_name='Портер')),
                ('movers', models.BooleanField(verbose_name='Грузчики')),
                ('furniture_assembly', models.BooleanField(verbose_name='Разборка/сборка мебели')),
                ('garbage_removal', models.BooleanField(verbose_name='Вызов мусора')),
                ('description', models.TextField(blank=True, verbose_name='Описание(Необязательное поле)')),
            ],
        ),
    ]
